import type { Metadata } from "next";
import { Bubblegum_Sans, Open_Sans } from "next/font/google";
import "./globals.css";

const bubblegumSans = Bubblegum_Sans({
  variable: "--font-bubblegum-sans",
  weight: "400",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${bubblegumSans.variable} ${openSans.variable}`}>
      <body>{children}</body>
    </html>
  );
}
