import type { Metadata } from "next";
import { Bubblegum_Sans, Poppins } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const bubblegumSans = Bubblegum_Sans({
  variable: "--font-bubblegum-sans",
  weight: "400",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${bubblegumSans.variable} ${poppins.variable}`} suppressHydrationWarning>
      <head />
      <body>
        <script
          suppressHydrationWarning
          dangerouslySetInnerHTML={{
            __html: `
              try {
                const theme = localStorage.getItem('dashboard-theme') || 'light';
                const highContrast = localStorage.getItem('high-contrast');
                if (theme === 'light') {
                  document.documentElement.classList.add('light-theme');
                } else {
                  document.documentElement.classList.remove('light-theme');
                }
                if (highContrast === 'true') {
                  document.documentElement.classList.add('high-contrast');
                } else {
                  document.documentElement.classList.remove('high-contrast');
                }
              } catch (e) {}
            `,
          }}
        />
        {children}
      </body>
    </html>
  );
}
