import { CaptionStyleToken } from '../../types/captions';

export const CAPTION_STYLES: CaptionStyleToken[] = [
  {
    id: 'none',
    name: 'None',
    animationType: 'none',
    fontFamily: 'Inter, sans-serif',
    fontWeight: 700,
    textColor: '#ffffff',
    accentColor: '#3a3a3d',
  },
  {
    id: 'hormozi',
    name: 'Bellatrix',
    animationType: 'hormoziPop', 
    fontFamily: 'Inter, sans-serif',
    fontWeight: 900,
    textColor: '#39ff14',
    accentColor: '#39ff14',
    italic: true,
    uppercase: true,
  },
  {
    id: 'karaoke',
    name: 'Alvcone Blue',
    animationType: 'karaokeSweep',
    fontFamily: 'Inter, sans-serif',
    fontWeight: 900,
    textColor: '#7e22ce',
    accentColor: '#7e22ce',
    italic: true,
    uppercase: true,
  },
  {
    id: 'bounce',
    name: 'Pacific',
    animationType: 'bouncingBox', 
    fontFamily: 'Inter, sans-serif',
    fontWeight: 800,
    textColor: '#ffffff',
    background: '#3730a3',
    accentColor: '#ffffff',
    uppercase: true,
  },
  {
    id: 'slide',
    name: 'Cartwheel Blue',
    animationType: 'slidingBox',
    fontFamily: 'Inter, sans-serif',
    fontWeight: 900,
    textColor: '#000000',
    background: '#34d399',
    accentColor: '#000000',
    uppercase: true,
  },
  {
    id: 'typewriter',
    name: 'Nova',
    animationType: 'typewriterFade',
    fontFamily: 'var(--font-poppins), sans-serif',
    fontWeight: 600,
    textColor: '#ffffff',
    accentColor: '#ffffff',
  },
  {
    id: 'highlight',
    name: 'Vitamin B',
    animationType: 'wordHighlight',
    fontFamily: 'Inter, sans-serif',
    fontWeight: 800,
    textColor: '#ffffff',
    background: '#3b82f6',
    accentColor: '#3b82f6',
    uppercase: true,
  },
  {
    id: 'cinematic',
    name: 'Quintessence',
    animationType: 'cinematicFade',
    fontFamily: 'serif',
    fontWeight: 400,
    textColor: '#eab308',
    accentColor: '#eab308',
  },
];

export const getCaptionStyle = (id: string): CaptionStyleToken =>
  CAPTION_STYLES.find((s) => s.id === id) ?? CAPTION_STYLES[0];
